name: CI|CD action

on:
    push:
        branches: [main]

jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Lint with flake8
          run: flake8 . --exclude migrations --ignore E501,F401,E302,W293,W391,W292

