name: CI|CD action

on:
    push:
        branches: [main]

jobs:
    testing:
      runs-on: ubuntu-latest
      env:
          NAME: ${{secrets.NAME}}
          DJANGO_DB_USER: ${{secrets.DJANGO_DB_USER}}
          PASSWORD: ${{secrets.PASSWORD}}
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
      services:
          postgres_nmain:
              image: postgres:latest
              env:
                  POSTGRES_USERS: ${{ env.DJANGO_DB_USER}}
                  POSTGRES_PASSWORD: ${{ env.PASSWORD}}
                  POSTGRES_DB: ${{ env.NAME}}
              ports:
                  - 5432:5432
              options:
                  --health-cmd pg_isready
                  --health-interval 5s
                  --health-timeout 5s
                  --health-retries 5
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
              clean: true

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Lint with flake8
          run: flake8 . --exclude migrations --ignore E501,F401,E302,W293,W391,W292

        - name: Tests
          run: python manage.py test
          env:
            NAME: ${{env.NAME}}
            DJANGO_DB_USER: ${{env.DJANGO_DB_USER}}
            PASSWORD: ${{env.PASSWORD}}
            HOST: ${{env.HOST}}
            PORT: ${{env.PORT}}

    deploy:
      runs-on: ubuntu-latest
      needs: testing
      steps:
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: 89.111.169.174
            username: ${{secrets.USERNAME}}
            password: ${{secrets.PASSWORD_SERVER}}
            script: |
              cd /home/vera/djangoNetology_m2m_relations_regru
              git pull
              sudo systemctl restart gunicorn
